Failure # 1 (occurred at 2021-12-01_12-04-06)
Traceback (most recent call last):
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 471, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 430, in fetch_result
    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/worker.py", line 1538, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AttributeError): [36mray::PPO.train()[39m (pid=50040, ip=10.116.70.179)
  File "python/ray/_raylet.pyx", line 479, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 432, in ray._raylet.execute_task.function_executor
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 519, in train
    raise e
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 508, in train
    result = Trainable.train(self)
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/tune/trainable.py", line 332, in train
    result = self.step()
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 110, in step
    res = next(self.train_exec_impl)
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/util/iter.py", line 758, in __next__
    return next(self.built_iterator)
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/util/iter.py", line 785, in apply_foreach
    for item in it:
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/util/iter.py", line 785, in apply_foreach
    for item in it:
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/util/iter.py", line 845, in apply_filter
    for item in it:
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/util/iter.py", line 845, in apply_filter
    for item in it:
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/util/iter.py", line 785, in apply_foreach
    for item in it:
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/util/iter.py", line 785, in apply_foreach
    for item in it:
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/util/iter.py", line 785, in apply_foreach
    for item in it:
  [Previous line repeated 1 more time]
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/util/iter.py", line 878, in apply_flatten
    for item in it:
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/util/iter.py", line 830, in add_wait_hooks
    item = next(it)
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/util/iter.py", line 785, in apply_foreach
    for item in it:
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/util/iter.py", line 785, in apply_foreach
    for item in it:
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/util/iter.py", line 785, in apply_foreach
    for item in it:
  [Previous line repeated 1 more time]
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/util/iter.py", line 472, in base_iterator
    yield ray.get(futures, timeout=timeout)
ray.exceptions.RayTaskError(AttributeError): [36mray::RolloutWorker.par_iter_next()[39m (pid=50036, ip=10.116.70.179)
  File "/home/semantibasu/smarts_new/SMARTS/smarts/core/smarts.py", line 220, in _step
    provider_state = self._step_providers(all_agent_actions, dt)
  File "/home/semantibasu/smarts_new/SMARTS/smarts/core/smarts.py", line 699, in _step_providers
    provider, actions, dt, self._elapsed_sim_time
  File "/home/semantibasu/smarts_new/SMARTS/smarts/core/smarts.py", line 738, in _step_provider
    provider_state = provider.step(provider_actions, dt, elapsed_sim_time)
  File "/home/semantibasu/smarts_new/SMARTS/smarts/core/sumo_traffic_simulation.py", line 341, in step
    self._traci_conn.simulationStep(self._cumulative_sim_seconds)
  File "/usr/share/sumo/tools/traci/connection.py", line 315, in simulationStep
    result = self._sendCmd(tc.CMD_SIMSTEP, None, None, "D", step)
  File "/usr/share/sumo/tools/traci/connection.py", line 181, in _sendCmd
    return self._sendExact()
  File "/usr/share/sumo/tools/traci/connection.py", line 91, in _sendExact
    raise FatalTraCIError("connection closed by SUMO")
traci.exceptions.FatalTraCIError: connection closed by SUMO

During handling of the above exception, another exception occurred:

[36mray::RolloutWorker.par_iter_next()[39m (pid=50036, ip=10.116.70.179)
  File "python/ray/_raylet.pyx", line 474, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 478, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 479, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 432, in ray._raylet.execute_task.function_executor
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/util/iter.py", line 1156, in par_iter_next
    return next(self.local_it)
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 281, in gen_rollouts
    yield self.sample()
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 563, in sample
    batches = [self.input_reader.next()]
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 71, in next
    batches = [self.get_data()]
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 181, in get_data
    item = next(self.rollout_provider)
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 569, in _env_runner
    base_env.send_actions(actions_to_send)
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/rllib/env/base_env.py", line 398, in send_actions
    obs, rewards, dones, infos = env.step(agent_dict)
  File "/home/semantibasu/smarts_new/SMARTS/benchmark/wrappers/rllib/frame_stack.py", line 191, in step
    agent_actions
  File "/home/semantibasu/smarts_new/SMARTS/benchmark/wrappers/rllib/wrapper.py", line 74, in step
    return self.env.step(agent_actions)
  File "/home/semantibasu/smarts_new/SMARTS/smarts/env/rllib_hiway_env.py", line 103, in step
    observations, rewards, dones, extras = self._smarts.step(agent_actions)
  File "/home/semantibasu/smarts_new/SMARTS/smarts/core/smarts.py", line 182, in step
    self.destroy()
  File "/home/semantibasu/smarts_new/SMARTS/smarts/core/smarts.py", line 455, in destroy
    self.teardown()
  File "/home/semantibasu/smarts_new/SMARTS/smarts/core/smarts.py", line 434, in teardown
    self._traffic_sim.teardown()
  File "/home/semantibasu/smarts_new/SMARTS/smarts/core/sumo_traffic_simulation.py", line 310, in teardown
    self._remove_vehicles()
  File "/home/semantibasu/smarts_new/SMARTS/smarts/core/sumo_traffic_simulation.py", line 300, in _remove_vehicles
    self._traci_conn.vehicle.remove(vehicle_id)
  File "/usr/share/sumo/tools/traci/_vehicle.py", line 1593, in remove
    self._setCmd(tc.REMOVE, vehID, "b", reason)
  File "/usr/share/sumo/tools/traci/domain.py", line 189, in _setCmd
    self._connection._sendCmd(self._cmdSetID, varID, objectID, format, *values)
  File "/usr/share/sumo/tools/traci/connection.py", line 181, in _sendCmd
    return self._sendExact()
  File "/usr/share/sumo/tools/traci/connection.py", line 82, in _sendExact
    if self._socket is None:
AttributeError: 'Connection' object has no attribute '_socket'

Failure # 2 (occurred at 2021-12-01_12-04-29)
Traceback (most recent call last):
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 471, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 430, in fetch_result
    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/worker.py", line 1538, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AttributeError): [36mray::PPO.train()[39m (pid=50035, ip=10.116.70.179)
  File "python/ray/_raylet.pyx", line 479, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 432, in ray._raylet.execute_task.function_executor
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 519, in train
    raise e
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 508, in train
    result = Trainable.train(self)
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/tune/trainable.py", line 332, in train
    result = self.step()
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 110, in step
    res = next(self.train_exec_impl)
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/util/iter.py", line 758, in __next__
    return next(self.built_iterator)
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/util/iter.py", line 785, in apply_foreach
    for item in it:
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/util/iter.py", line 785, in apply_foreach
    for item in it:
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/util/iter.py", line 845, in apply_filter
    for item in it:
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/util/iter.py", line 845, in apply_filter
    for item in it:
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/util/iter.py", line 785, in apply_foreach
    for item in it:
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/util/iter.py", line 785, in apply_foreach
    for item in it:
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/util/iter.py", line 785, in apply_foreach
    for item in it:
  [Previous line repeated 1 more time]
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/util/iter.py", line 878, in apply_flatten
    for item in it:
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/util/iter.py", line 830, in add_wait_hooks
    item = next(it)
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/util/iter.py", line 785, in apply_foreach
    for item in it:
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/util/iter.py", line 785, in apply_foreach
    for item in it:
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/util/iter.py", line 785, in apply_foreach
    for item in it:
  [Previous line repeated 1 more time]
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/util/iter.py", line 472, in base_iterator
    yield ray.get(futures, timeout=timeout)
ray.exceptions.RayTaskError(AttributeError): [36mray::RolloutWorker.par_iter_next()[39m (pid=50046, ip=10.116.70.179)
  File "/home/semantibasu/smarts_new/SMARTS/smarts/core/smarts.py", line 220, in _step
    provider_state = self._step_providers(all_agent_actions, dt)
  File "/home/semantibasu/smarts_new/SMARTS/smarts/core/smarts.py", line 699, in _step_providers
    provider, actions, dt, self._elapsed_sim_time
  File "/home/semantibasu/smarts_new/SMARTS/smarts/core/smarts.py", line 738, in _step_provider
    provider_state = provider.step(provider_actions, dt, elapsed_sim_time)
  File "/home/semantibasu/smarts_new/SMARTS/smarts/core/sumo_traffic_simulation.py", line 341, in step
    self._traci_conn.simulationStep(self._cumulative_sim_seconds)
  File "/usr/share/sumo/tools/traci/connection.py", line 315, in simulationStep
    result = self._sendCmd(tc.CMD_SIMSTEP, None, None, "D", step)
  File "/usr/share/sumo/tools/traci/connection.py", line 181, in _sendCmd
    return self._sendExact()
  File "/usr/share/sumo/tools/traci/connection.py", line 91, in _sendExact
    raise FatalTraCIError("connection closed by SUMO")
traci.exceptions.FatalTraCIError: connection closed by SUMO

During handling of the above exception, another exception occurred:

[36mray::RolloutWorker.par_iter_next()[39m (pid=50046, ip=10.116.70.179)
  File "python/ray/_raylet.pyx", line 474, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 478, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 479, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 432, in ray._raylet.execute_task.function_executor
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/util/iter.py", line 1156, in par_iter_next
    return next(self.local_it)
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 281, in gen_rollouts
    yield self.sample()
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 563, in sample
    batches = [self.input_reader.next()]
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 71, in next
    batches = [self.get_data()]
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 181, in get_data
    item = next(self.rollout_provider)
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 569, in _env_runner
    base_env.send_actions(actions_to_send)
  File "/home/semantibasu/.venv/lib/python3.7/site-packages/ray/rllib/env/base_env.py", line 398, in send_actions
    obs, rewards, dones, infos = env.step(agent_dict)
  File "/home/semantibasu/smarts_new/SMARTS/benchmark/wrappers/rllib/frame_stack.py", line 191, in step
    agent_actions
  File "/home/semantibasu/smarts_new/SMARTS/benchmark/wrappers/rllib/wrapper.py", line 74, in step
    return self.env.step(agent_actions)
  File "/home/semantibasu/smarts_new/SMARTS/smarts/env/rllib_hiway_env.py", line 103, in step
    observations, rewards, dones, extras = self._smarts.step(agent_actions)
  File "/home/semantibasu/smarts_new/SMARTS/smarts/core/smarts.py", line 182, in step
    self.destroy()
  File "/home/semantibasu/smarts_new/SMARTS/smarts/core/smarts.py", line 455, in destroy
    self.teardown()
  File "/home/semantibasu/smarts_new/SMARTS/smarts/core/smarts.py", line 434, in teardown
    self._traffic_sim.teardown()
  File "/home/semantibasu/smarts_new/SMARTS/smarts/core/sumo_traffic_simulation.py", line 310, in teardown
    self._remove_vehicles()
  File "/home/semantibasu/smarts_new/SMARTS/smarts/core/sumo_traffic_simulation.py", line 300, in _remove_vehicles
    self._traci_conn.vehicle.remove(vehicle_id)
  File "/usr/share/sumo/tools/traci/_vehicle.py", line 1593, in remove
    self._setCmd(tc.REMOVE, vehID, "b", reason)
  File "/usr/share/sumo/tools/traci/domain.py", line 189, in _setCmd
    self._connection._sendCmd(self._cmdSetID, varID, objectID, format, *values)
  File "/usr/share/sumo/tools/traci/connection.py", line 181, in _sendCmd
    return self._sendExact()
  File "/usr/share/sumo/tools/traci/connection.py", line 82, in _sendExact
    if self._socket is None:
AttributeError: 'Connection' object has no attribute '_socket'

